{% set name = "uri_template" %}
{% set version = "0.7.0" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  - url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
    sha256: 312c8fe13700db86ac9d05ea997af3db03abdf50c65b1801d775bc7a695f185d

build:
  noarch: generic
  number: 1
  script:
    - gem install -N -l -V --norc --ignore-dependencies {{ name }}-{{ version }}.gem

requirements:
  host:
    - ruby >=2.7,<3
  run:
    - ruby >=2.7,<3
test:
  commands:
    - ruby -r {{ name }} -e 'exit 0'

about:
  home: https://rubygems.org/gems/{{ name }}
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A templating system for URIs, which implements RFC6570 and Colon based URITemplates in a clean and straight forward way
  doc_url: https://www.rubydoc.info/gems/{{ name }}
  dev_url: https://github.com/hannesg/uri_template

extra:
  recipe-maintainers:
    - svengiegerich
    - janjagusch
